export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_ENTRIES = 'SET_ENTRIES';
export const SET_SUMMARY = 'SET_SUMMARY';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_APP_LOADING = 'SET_APP_LOADING';